services:
  snidust:
    container_name: snidust
    restart: unless-stopped
    image: 'ghcr.io/sygix/snidust:main'
    environment:
      - TZ=${TZ:-Europe/Paris}
      - ALLOWED_CLIENTS=${ALLOWED_CLIENTS:-127.0.0.1/32, myDynDNSDomain.changeip.co}
      - EXTERNAL_IP=${EXTERNAL_IP:-10.111.123.8}
      - SPOOF_ALL_DOMAINS=${SPOOF_ALL_DOMAINS:-false}
    # ports:
    #     - '443:8443'
    #     - '80:8080'
    #     - '53:5300/udp'
    #     - '853:853/tcp'
    cap_add:
      - NET_BIND_SERVICE
    networks: 
      macvlan:
        ipv4_address: 192.168.1.4
        ipv6_address: 2001:db8:1234::4

networks:
  macvlan:
    external: true